# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MamaKitchenApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MamaKitchenApp
  
    pod 'Alamofire'
    pod 'CountryPickerView', '~> 3.2.0'
    pod 'Kingfisher'
    pod 'OTPFieldView'

  target 'MamaKitchenAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MamaKitchenAppUITests' do
    # Pods for testing
  end

end
